services:
  - type: web
    name: ColorMeCraftyClient
    env: node
    plan: free
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm start
    envVars:
      - key: REACT_APP_COLORWAYS_API_KEY
        value: YOUR_RAPIDAPI_KEY
      - key: SECRET_KEY
        value: YOUR_SECRET_KEY

  - type: web
    name: ColorMeCraftyServer
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && node app.js
    envVars:
      - key: SECRET_KEY
        value: YOUR_SECRET_KEY
      - key: ANOTHER_ENV_VAR
        value: YOUR_ENV_VAR_VALUE